### ISSUE TITLE
Visual Studio Code Manifest wrong

### ISSUE THREAD

**Issue by EoD** [miramir/miramir-layman#7]
When I try to install VS Code 1.19.x, I end up with checksum errors. Both 1.19.1 and 1.19.2

```
!!! Fetched file: visual-studio-code-1.19.1-amd64.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      66903595
!!! Expected: 66905942
```

Did you consider proxy-maintaining the package on the Gentoo tree? It seems to have no in-overlay dependencies.

**Comment by kroppt** [comment]
This still happens. When emerging, the latest version of vscode is downloaded, which is almost never the version being installed, due to the overlay being out of date.

**Comment by miramir** [comment]
Скорее всего всё уже работает.
